version: "3.9"

services:
  pg-dados:
    image: postgres:15
    container_name: pg-dados
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl-filmes:
    build: etl/.
    container_name: etl-filmes
    depends_on:
      - pg-dados
    env_file: .env
    volumes:
      - ./data:/app/data

volumes:
  pgdata:

networks:
  default:
    driver: bridge
